const KZY_API='https://kzy.zmanimscreens.com/api/data';
const SHABBOS_LABELS=['לקראת שבת','מנחה א׳','פלג המנחה','הדלקת נרות','מנחה ב׳','שקיעה','שיעור','שחרית','סו״ז קריאת שמע מג״א','סו״ז קריאת שמע גר״א','מנחה א׳','שיעור','מנחה ב׳','שקיעה','פרקי אבות','מעריב','צאת הכוכבים ר״ת'];
const WEEKDAY_LABELS=['שחרית א׳','שחרית ב׳','שחרית ראשון / חג','מנחה מוקדמת','מנחה מאוחרת א׳','מנחה מאוחרת ב׳','מעריב בשקיעה','מעריב','מעריב'];
const state={friday:null, shabbos:[], weekday:[], raw:null};
const $=s=>document.querySelector(s);
function localISO(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function comingFriday(from=new Date()){const d=new Date(from);d.setHours(12,0,0,0);let add=(5-d.getDay()+7)%7;if(add===0&&d.getDay()!==5)add=7;d.setDate(d.getDate()+add);return d}
function setFriday(d){state.friday=new Date(d);$('#friday').value=localISO(state.friday);renderTitle();render()}
function renderTitle(){const sat=new Date(state.friday);sat.setDate(sat.getDate()+1);$('#weekTitle').textContent=`Shabbos of ${sat.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}`;$('#panelDate').textContent=`${state.friday.toLocaleDateString('en-US',{month:'short',day:'numeric'})} – ${sat.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}`}
function normalizeTime(v){if(v==null)return'';if(typeof v==='string')return v.replace(/^0/,'').trim();return String(v)}
function boxes(raw){return Array.isArray(raw)?raw:(raw?.boxes||raw?.data||[])}
function findBox(raw,name){return boxes(raw).find(b=>String(b.position||b.name||'').toLowerCase()===name)}
function orderedRows(box){const r=box?.rows||box?.items||box?.data||[];return [...r].sort((a,b)=>(a.order??0)-(b.order??0))}
function displayRow(r){const text=String(r.text||r.label||'').trim();const time=normalizeTime(r.time);if(r.type==='time')return {label:text,time,source:'KZY fixed'};if(r.type==='text')return {label:text,time,source:'KZY text'};const mins=Number(r.minutes||0);const from=r.from||'';const offset=r.offset||'';let rule=from?`${mins?Math.abs(mins)+' min ':''}${offset||''} ${from}`.trim():'Automatic';return {label:text,time:time||'AUTO',source:rule}}
async function refresh(){const status=$('#status');status.textContent='Loading KZY…';try{const res=await fetch(KZY_API,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const raw=await res.json();state.raw=raw;const sb=orderedRows(findBox(raw,'shabbos')).map(displayRow);const wd=orderedRows(findBox(raw,'weekday')).map(displayRow);state.shabbos=sb.length?sb:SHABBOS_LABELS.map(label=>({label,time:'',source:'Not mapped'}));state.weekday=wd.length?wd:WEEKDAY_LABELS.map(label=>({label,time:'',source:'Not mapped'}));$('#sourceNotice').textContent=`Loaded live KZY schedule • ${new Date().toLocaleTimeString()}`;status.textContent='KZY loaded';render()}catch(e){state.shabbos=SHABBOS_LABELS.map(label=>({label,time:'',source:'Manual'}));state.weekday=WEEKDAY_LABELS.map(label=>({label,time:'',source:'Manual'}));$('#sourceNotice').textContent=`Could not load KZY API in this browser (${e.message}). Manual editing still works.`;status.textContent='Manual mode';render()}}
function editorRows(){const all=[...state.shabbos.map((r,i)=>({group:'shabbos',i,r})),...state.weekday.map((r,i)=>({group:'weekday',i,r}))];$('#fields').innerHTML=all.map(x=>`<div class="field"><label>${x.r.label||'(unnamed)'} <small title="${x.r.source||''}">· ${x.r.source||''}</small></label><input data-group="${x.group}" data-i="${x.i}" value="${x.r.time||''}"></div>`).join('');$('#fields').querySelectorAll('input').forEach(el=>el.addEventListener('input',()=>{state[el.dataset.group][+el.dataset.i].time=el.value;renderPanel()}))}
function rowsHTML(rows){return rows.map(r=>`<div class="schedule-row"><div class="label">${r.label||''}</div><div class="time">${r.time||'—'}</div></div>`).join('')}
function renderPanel(){$('#panelRows').innerHTML=rowsHTML(state.shabbos);$('#weekdayRows').innerHTML=rowsHTML(state.weekday)}
function render(){editorRows();renderPanel()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]))}
function exportSVG(){const W=620,pad=42,rowH=31;const rows=[...state.shabbos,{section:true,label:'זמני ימי החול'},...state.weekday];const H=120+rows.length*rowH+35;let y=82;let body='';for(const r of rows){if(r.section){y+=18;body+=`<text x="${W-pad}" y="${y}" text-anchor="end" class="section">${esc(r.label)}</text><line x1="${pad}" x2="${W-pad}" y1="${y+10}" y2="${y+10}" class="heavy"/>`;y+=24;continue}body+=`<text x="${W-pad}" y="${y}" text-anchor="end" class="label">${esc(r.label)}</text><text x="${pad}" y="${y}" class="time">${esc(r.time||'—')}</text><line x1="${pad}" x2="${W-pad}" y1="${y+9}" y2="${y+9}" class="line"/>`;y+=rowH}const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><style>.title,.section,.label{font-family:Arial,sans-serif;direction:rtl;unicode-bidi:bidi-override;fill:#18263e}.title{font-size:29px;font-weight:700}.section{font-size:20px;font-weight:700}.label{font-size:15px}.time{font-family:Arial,sans-serif;font-size:15px;font-weight:700;fill:#172238}.line{stroke:#ddd9d0;stroke-width:1}.heavy{stroke:#18263e;stroke-width:2}</style><text x="${W-pad}" y="42" text-anchor="end" class="title">זמני שבת</text><line x1="${pad}" x2="${W-pad}" y1="58" y2="58" class="heavy"/>${body}</svg>`;const blob=new Blob([svg],{type:'image/svg+xml;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='KZY-Weekly-Zmanim.svg';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#prev').onclick=()=>{const d=new Date(state.friday);d.setDate(d.getDate()-7);setFriday(d)};$('#next').onclick=()=>{const d=new Date(state.friday);d.setDate(d.getDate()+7);setFriday(d)};$('#thisWeek').onclick=()=>setFriday(comingFriday());$('#friday').onchange=e=>setFriday(new Date(`${e.target.value}T12:00:00`));$('#refresh').onclick=refresh;$('#exportSvg').onclick=exportSVG;setFriday(comingFriday());refresh();